# Generated by Django 5.2.12 on 2026-05-12 20:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('plants', models.JSONField()),
                ('frequency', models.CharField(max_length=20)),
                ('custom_days', models.JSONField(blank=True, default=list)),
                ('day_of_week', models.JSONField(blank=True, default=list)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reminders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoverPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('plant_name_ur', models.CharField(blank=True, db_column='name_ur', max_length=100, null=True)),
                ('photo_url', models.TextField(db_column='photo')),
                ('family', models.CharField(blank=True, db_column='family', max_length=100, null=True)),
                ('family_ur', models.CharField(blank=True, db_column='family_ur', max_length=200, null=True)),
                ('origin', models.CharField(blank=True, db_column='origin', max_length=100, null=True)),
                ('origin_ur', models.CharField(blank=True, db_column='origin_ur', max_length=150, null=True)),
                ('light', models.CharField(blank=True, db_column='light', max_length=50, null=True)),
                ('light_ur', models.CharField(blank=True, db_column='light_ur', max_length=150, null=True)),
                ('height', models.CharField(blank=True, db_column='height', max_length=50, null=True)),
                ('height_ur', models.CharField(blank=True, db_column='height_ur', max_length=100, null=True)),
                ('watering', models.CharField(blank=True, db_column='watering', max_length=50, null=True)),
                ('watering_ur', models.CharField(blank=True, db_column='watering_ur', max_length=100, null=True)),
                ('toxicity', models.CharField(blank=True, db_column='toxicity', max_length=50, null=True)),
                ('toxicity_ur', models.CharField(blank=True, db_column='toxicity_ur', max_length=200, null=True)),
                ('uses', models.TextField(blank=True, db_column='uses', null=True)),
                ('uses_ur', models.TextField(blank=True, db_column='uses_ur', null=True)),
                ('interesting_facts', models.TextField(blank=True, db_column='interesting_facts', null=True)),
                ('interesting_facts_ur', models.TextField(blank=True, db_column='interesting_facts_ur', null=True)),
            ],
            options={
                'db_table': 'discover_plants',
            },
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ur', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fun_fact',
            },
        ),
        migrations.CreateModel(
            name='HerbalVault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_ur', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('family_ur', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_ur', models.CharField(blank=True, max_length=100, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('scientific_name_ur', models.CharField(blank=True, max_length=150, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('height_ur', models.CharField(blank=True, max_length=50, null=True)),
                ('light', models.CharField(blank=True, max_length=50, null=True)),
                ('light_ur', models.CharField(blank=True, max_length=50, null=True)),
                ('watering', models.CharField(blank=True, max_length=50, null=True)),
                ('watering_ur', models.CharField(blank=True, max_length=50, null=True)),
                ('toxicity', models.CharField(blank=True, max_length=50, null=True)),
                ('toxicity_ur', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('type_ur', models.CharField(blank=True, max_length=50, null=True)),
                ('usda_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('usda_zone_ur', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('about_ur', models.TextField(blank=True, null=True)),
                ('key_benefits', models.JSONField(blank=True, default=list)),
                ('key_benefits_ur', models.JSONField(blank=True, default=list)),
                ('usage_data', models.JSONField(blank=True, default=list)),
                ('usage_data_ur', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'herbal_vault',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tutorials',
            },
        ),
        migrations.CreateModel(
            name='PlantJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plant_journal',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.post')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.post')),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
