# Generated by Django 6.0 on 2026-03-08 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('photo_url', models.TextField(db_column='photo')),
                ('family', models.CharField(blank=True, db_column='family', max_length=100, null=True)),
                ('origin', models.CharField(blank=True, db_column='origin', max_length=100, null=True)),
                ('light', models.CharField(blank=True, db_column='light', max_length=50, null=True)),
                ('height', models.CharField(blank=True, db_column='height', max_length=50, null=True)),
                ('watering', models.CharField(blank=True, db_column='watering', max_length=50, null=True)),
                ('toxicity', models.CharField(blank=True, db_column='toxicity', max_length=50, null=True)),
                ('uses', models.TextField(blank=True, db_column='uses', null=True)),
                ('interesting_facts', models.TextField(blank=True, db_column='interesting_facts', null=True)),
            ],
            options={
                'db_table': 'discover_plants',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
