# Generated by Django 6.0 on 2026-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerbalVault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('watering', models.CharField(blank=True, max_length=50, null=True)),
                ('toxicity', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('usda_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('key_benefits', models.JSONField(blank=True, default=list)),
                ('usage_data', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
