# Generated by Django 6.0 on 2026-03-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_herbalvault'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='herbalvault',
            table='herbal_vault',
        ),
    ]
