# Generated by Django 6.0 on 2026-03-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_herbalvault_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbalvault',
            name='light',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
