# Generated by Django 6.0 on 2026-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_herbalvault_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbalvault',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='herbalvault',
            table=None,
        ),
    ]
