# Generated by Django 6.0 on 2026-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_herbalvault_about_alter_herbalvault_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbalvault',
            name='featured_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='herbalvault',
            table='herbal_vault',
        ),
    ]
