# Generated by Django 6.0 on 2026-03-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_herbalvault_featured_date_alter_herbalvault_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herbalvault',
            name='featured_date',
        ),
        migrations.AddField(
            model_name='herbalvault',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
