# Generated by Django 6.0 on 2026-03-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_herbalvault_featured_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herbalvault',
            name='featured',
        ),
    ]
